### PR TITLE
Fix moded arguments causes exception, fix #13

### LINKED ISSUE #13: 使用Lightfall核心，无法从登陆服进入1.16.5 Arclight 模组服
### 我正在运行

* **Arclight** [-1.16.5-1.0.20] 

* **你确认这是最新版吗** [是]

* **你确认所有Mod都安装了依赖** [是]

* **你确认所有插件都已更新至对应版本** [是]

* **Java** [11] 

* **操作系统** [Windows 10]

  

* **插件列表** 
LuckPerms, PlaceholderAPI, ClearLag, PlugMan, BetterRandTp, WorldBorder, Vault, Multiverse-Core, ProtocolLib, ChestCommands, MiaoChat, Essentials, EssentialsProtect, EssentialsChat, EssentialsAntiBuild, AncientGates, ColorMOTD, TAB, HolographicDisplays, EssentialsSpawn, AuthMe

* **Mod 列表** 
• mods_folder tetra-1.16.5-3.14.1.jar : tetra (3.14.1) - 1
• mods_folder rhino-1605.1.1-build.23.jar : rhino (1605.1.1-build.23) - 1
• mods_folder UnionLib-1.16.5-3.3.2.jar : unionlib (3.3.2) - 1
• mods_folder Cucumber-1.16.4-4.1.9.jar : cucumber (4.1.9) - 1
• mods_folder primalwinter-forge-1.16.4-2.0.5.jar : primalwinter (2.0.5) - 1
• mods_folder ExtendedCrafting-1.16.4-3.1.5.jar : extendedcrafting (3.1.5) - 1
• mods_folder RopeBridge-1.16.5-2.2.1.jar : ropebridge (1.16.5-2.2.1) - 1
• mods_folder bdlib-1.16.1.7-mc1.16.5.jar : bdlib (1.16.1.7) - 1
• mods_folder BetterCaves-Forge-1.16.4-1.1.2.jar : bettercaves (1.16.4-1.1.2) - 1
• mods_folder PassableFoliage-1.16.5-2.2.1.jar : passablefoliage (2.2.1) - 1
• mods_folder ForgeEndertech-1.16.4-7.1.0.0-build.0075.jar : forgeendertech (7.1.0.0) - 1
• mods_folder mgui-1.16.5-3.2.0.jar : mgui (3.2.0) - 1
• mods_folder Controlling-7.0.0.20.jar : controlling (7.0.0.20) - 1
• mods_folder Placebo-1.16.4-4.5.0.jar : placebo (4.5.0) - 1
• mods_folder comforts-forge-1.16.5-4.0.0.4.jar : comforts (1.16.5-4.0.0.4) - 1
• mods_folder YungsApi-1.16.4-Forge-6.jar : yungsapi (1.16.4-Forge-6) - 1
• mods_folder AdHooks-1.16.4-6.1.5.0-build.0124.jar : adhooks (6.1.5.0) - 1
• mods_folder tetranomicon-1.3.jar : tetranomicon (1.3) - 1
• mods_folder Morpheus-1.16.5-4.2.70.jar : morpheus (4.2.70) - 1
• mods_folder ironagefurniture 1.16.4-1.16.5 0.2.0.5.jar : ironagefurniture (1.16.4-0.2.0) - 1
• mods_folder Hwyla-forge-1.10.11-B78_1.16.2.jar : waila (1.10.11-B78_1.16.2) - 1
• mods_folder Electrodynamics-1.16.5-0.4.0-1.jar : electrodynamics (1.16.5-0.4.0-1) - 1
• mods_folder stone-age-1.16.5-1.3.3.jar : stone_age (1.16.5-1.3.3) - 1
• mods_folder FpsReducer-mc1.16.5-1.19.jar : fpsreducer (mc1.16.5-1.19) - 1
• mods_folder CraftTweaker-1.16.5-7.1.0.313.jar : crafttweaker (7.1.0.313) - 1
• mods_folder ImmersivePetroleum-1.16.5-3.3.0-4.jar : immersivepetroleum (3.3.0-4) - 1
• maven_libs forge-1.16.5-36.2.0-universal.jar : forge (36.2.0) - 1
• mods_folder DynamicSurroundings-1.16.4-4.0.4.2.jar : dsurround (1.16.4-4.0.4.2) - 4
• mods_folder CharcoalPit[1.16.5]-2.14.jar : charcoal_pit (2.0) - 1
• mods_folder ironchest-1.16.4-11.2.10.jar : ironchest (1.16.4-11.2.10) - 1
• minecraft forge-1.16.5-36.2.0-server.jar : minecraft (1.16.5) - 1
• mods_folder valkyrielib-1.16.5-3.0.8.0.jar : valkyrielib (1.16.5-3.0.8.0) - 1
• mods_folder AdvancedRocketry-1.16.5-2.0.0-12-universal.jar : advancedrocketry (1.16.5-2.0.0-12) - 1
• mods_folder wildwestguns_1.16.5_11.jar : wildwestguns2 (1.0.0) - 1
• mods_folder towers_of_the_wild-1.16.4-2.0.1.jar : towers_of_the_wild (1.16.4-2.0.1) - 1
• mods_folder smoothboot-forge-1.16.4-1.2.2.jar : smoothboot (1.16.4-1.2.2) - 1
• mods_folder notreepunching-forge-1.16.5-4.2.0.jar : notreepunching (4.2.0) - 1
• mods_folder MasterfulMachinery-1.16.5-0.1.48-B358.jar : masterfulmachinery (1.16.5-0.1.48-B358) - 1
• mods_folder Patchouli-1.16.4-51.jar : patchouli (1.16.4-51) - 1
• mods_folder ftb-backups-2.1.1.6.jar : ftbbackups (2.1.1.6) - 1
• mods_folder diet-forge-1.16.5-0.33.jar : diet (1.16.5-0.33) - 1
• mods_folder FastWorkbench-1.16.4-4.5.1.jar : fastbench (4.5.1) - 1
• mods_folder advgenerators-0.10.1.9-mc1.16.5.jar : advgenerators (0.10.1.9) - 1
• mods_folder StorageDrawers-1.16.3-8.2.2.jar : storagedrawers (8.2.2) - 1
• mods_folder YungsExtras-Forge-1.16.4-1.0.jar : yungsextras (Forge-1.16.4-1.0) - 1
• mods_folder Nuclear Science-1.16.5-0.3.0-0.jar : nuclearscience (1.16.5-0.3.0-0) - 1
• mods_folder ages-api-1.16.5-1.2.0.jar : ages_api (1.16.5-1.2.0) - 1
• mods_folder elevatorid-1.16.5-1.7.13.jar : elevatorid (1.16.5-1.7.13) - 1
• mods_folder frostedheart-1.0.1.jar : frostedheart (1.0.0) - 1
• mods_folder ImmersiveEngineering-1.16.5-5.0.0-135.jar : immersiveengineering (1.16.5-5.0.0-135) - 1
• mods_folder Survive-1.16.5-3.3.1.jar : survive (1.16.5-3.3.1) - 1
• mods_folder obfuscate-0.6.2-1.16.3.jar : obfuscate (0.6.2) - 1
• mods_folder vehicle-mod-0.45.2-1.16.3.jar : vehicle (0.45.2) - 1
• mods_folder BetterStrongholds-1.16.4-1.1.jar : betterstrongholds (1.16.4-1.1) - 1
• mods_folder LibVulpes-1.16.5-1.0.2-25-universal.jar : libvulpes (1.16.5-1.0.2-25) - 1
• mods_folder cfm-7.0.0pre21-1.16.3.jar : cfm (7.0.0-pre21) - 1
• mods_folder architectury-1.20.28-forge.jar : architectury (1.20.28) - 1
• mods_folder ftb-library-forge-1605.3.1-build.48.jar : ftblibrary (1605.3.1-build.48) - 1
• mods_folder item-filters-forge-1605.2.5-build.9.jar : itemfilters (1605.2.5-build.9) - 1
• mods_folder ftb-teams-forge-1605.2.1-build.17.jar : ftbteams (1605.2.1-build.17) - 1
• mods_folder ftb-chunks-forge-1605.3.1-build.31.jar : ftbchunks (1605.3.1-build.31) - 1
• mods_folder kubejs-forge-1605.3.12-build.38.jar : kubejs (1605.3.12-build.38) - 1
• mods_folder ftb-quests-forge-1605.3.3-build.39.jar : ftbquests (1605.3.3-build.39) - 1
• mods_folder ftb-ranks-1605.1.4-build.7-forge.jar : ftbranks (1605.1.4-build.7) - 1
• mods_folder AppleSkin-mc1.16.2-forge-1.0.14.jar : appleskin (1.0.14) - 1
• mods_folder engineersdecor-1.16.4-1.1.13.jar : engineersdecor (1.1.13) - 1
• arclight arclight-forge-1.16.5-1.0.20.jar : arclight (1.16.5-1.0.20-368b0cb) - 1
• mods_folder AdChimneys-1.16.4-6.0.10.0-build.0125.jar : adchimneys (6.0.10.0) - 1
• mods_folder rankine-1.16.5-1.2.3-hotfix1.jar : rankine (1.2.3) - 1
• mods_folder BetterMineshafts-Forge-1.16.4-2.0.3.jar : bettermineshafts (1.16.4-2.0.3) - 1

### 错误描述

使用Lightfall核心，无法从登陆服进入1.16.5 Arclight 模组服。

### 重现步骤

1. 安装 Lightfall 和 Arclight

2. 进入登陆服，然后尝试登入1.16.5模组服

3. 出现报错，无法进入

 

**可在 Forge 复现** [是/否]

**可在 Spigot 复现** [是/否]

### 报错信息

[错误日志]

<details><pre>
[22:48:38 ERROR]: io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: No provider for argument crafttweaker:item_argument
[22:48:38 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98)
[22:48:38 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[22:48:38 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[22:48:38 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[22:48:38 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[22:48:38 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[22:48:38 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[22:48:38 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[22:48:38 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
[22:48:38 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311)
[22:48:38 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:432)
[22:48:38 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
[22:48:38 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[22:48:38 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[22:48:38 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[22:48:38 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[22:48:38 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[22:48:38 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[22:48:38 ERROR]:       at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[22:48:38 ERROR]:       at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
[22:48:38 ERROR]:       at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
[22:48:38 ERROR]:       at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
[22:48:38 ERROR]:       at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
[22:48:38 ERROR]:       at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
[22:48:38 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[22:48:38 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[22:48:38 ERROR]:       at java.lang.Thread.run(Unknown Source)
[22:48:38 ERROR]: Caused by: java.lang.IllegalArgumentException: No provider for argument crafttweaker:item_argument
[22:48:38 ERROR]:       at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
[22:48:38 ERROR]:       at net.md_5.bungee.protocol.packet.Commands$ArgumentRegistry.read(Commands.java:603)
[22:48:38 ERROR]:       at net.md_5.bungee.protocol.packet.Commands$ArgumentRegistry.access$000(Commands.java:308)
[22:48:38 ERROR]:       at net.md_5.bungee.protocol.packet.Commands.read(Commands.java:85)
[22:48:38 ERROR]:       at net.md_5.bungee.protocol.DefinedPacket.read(DefinedPacket.java:266)
[22:48:38 ERROR]:       at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:60)
[22:48:38 ERROR]:       at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:12)
[22:48:38 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
[22:48:38 ERROR]:       ... 26 more
[22:48:38 INFO]: [Evan] disconnected with: The server you were previously on went down, you have been connected to a fallback server
</pre></details>

### PR DESCRIPTION
**Pull request by khjxiaogu**
Added a default command parser to widely support mod provided arguments, tested all good

### CODE REVIEW

**Comment by IzzelAliz** [comment]
This is not how it works. This is handled in Arclight and you need to enable bungee mode.

https://github.com/IzzelAliz/Arclight/blob/20b21c4ce71303f9eb29a2c6b4a83d8412d48309/arclight-common/src/main/java/io/izzel/arclight/common/mixin/core/commands/synchronization/ArgumentTypesMixin.java#L56-L80

Closing.

**Comment by khjxiaogu** [comment]
This add more compatibility to other forge server brands.

**Comment by khjxiaogu** [comment]
And this also fix a problem with [corpse](https://www.curseforge.com/minecraft/mc-mods/corpse). That is you would being kicked when seeing a corpse on arclight server and lightfall

**Comment by IzzelAliz** [comment]
Other server is out of scope.

**Pull request closed without merging**
